#!/usr/bin/env bash
# Debug Fix
sudo rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx restart
