#!/usr/bin/env bash
#Prints 'Holberton School' 10 times, in the 9th iteration print 'Hi' as well.
i=0
while [ $i -lt 11 ]
    do 
    if [ $i = 9 ]
	    then 
	    echo "Hi"
else
    echo "Holberton School"
    fi
    let i+=1
done
