#!/usr/bin/env bash
#Prints 'Holberton School' 10 times, in the 4th iteration print 'bad luck' and in the 8th 'good luck' as well.
i=1
while [  $i -lt 11 ]
    do 
    if [ $i == 4 ]
	    then 
	    echo "bad luck"
    elif [ $i == 8 ]
	    then 
	    echo "good luck"
else
  	echo "Holberton School"
	fi
	i=$(( i+1 ))
done